const data = [
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-fashion-model-with-a-cold-and-pale-appearance-39877-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"11",
    },
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-cold-looking-fashion-woman-in-a-winter-environment-39879-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"11",
    },
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-photographer-portraying-a-woman-on-a-white-background-34423-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"11",
    },
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-elegantly-dressed-girl-during-a-photoshoot-34422-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"11",
    },
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-face-of-a-model-with-jewelry-posing-in-a-photoshoot-34425-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"11",
    },
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-model-in-gold-makeup-in-a-photoshoot-34424-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"11",
    },
    {
        "url": "https://assets.mixkit.co/videos/preview/mixkit-model-girl-posing-on-a-white-background-34428-large.mp4",
        "channel": "Motion",
        "song": "No Sound",
        "messages":"11",
        "description":"Portrait of a young fashion model of cold and pale appearance, with winter concept makeup, under a blue light in a cold environment",
        "shares":"500",
    },
]

export default data;